cities = [
  {
    "city": "San Francisco",
    "city_ascii": "San Francisco",
    "lat": 37.74000775,
    "lng": -122.4599777,
    "pop": 2091036,
    "country": "United States of America",
    "iso2": "US",
    "iso3": "USA",
    "province": "California",
    "state_ansi": "CA",
    "timezone": "America/Los_Angeles"
  },
  {
    "city": "Kyoto",
    "city_ascii": "Kyoto",
    "lat": 35.02999229,
    "lng": 135.7499979,
    "pop": 1632320,
    "country": "Japan",
    "iso2": "JP",
    "iso3": "JPN",
    "province": "Kyoto",
    "timezone": "Asia/Tokyo"
  },
  {
    "city": "San Martin",
    "city_ascii": "San Martin",
    "lat": -33.06998533,
    "lng": -68.49001612,
    "pop": 99974,
    "country": "Argentina",
    "iso2": "AR",
    "iso3": "ARG",
    "province": "Mendoza",
    "timezone": "America/Argentina/Mendoza"
  },
  {
    "city": "San Nicolas",
    "city_ascii": "San Nicolas",
    "lat": -33.33002114,
    "lng": -60.24000289,
    "pop": 117123.5,
    "country": "Argentina",
    "iso2": "AR",
    "iso3": "ARG",
    "province": "Ciudad de Buenos Aires",
    "timezone": "America/Argentina/Buenos_Aires"
  },
  {
    "city": "San Francisco",
    "city_ascii": "San Francisco",
    "lat": -31.43003375,
    "lng": -62.08996749,
    "pop": 43231,
    "country": "Argentina",
    "iso2": "AR",
    "iso3": "ARG",
    "province": "Córdoba",
    "timezone": "America/Argentina/Cordoba"
  },
  {
    "city": "San Lorenzo",
    "city_ascii": "San Lorenzo",
    "lat": -28.12000324,
    "lng": -58.76998926,
    "pop": 25833.5,
    "country": "Argentina",
    "iso2": "AR",
    "iso3": "ARG",
    "province": "Corrientes",
    "timezone": "America/Argentina/Cordoba"
  },
  {
    "city": "San Antonio Oeste",
    "city_ascii": "San Antonio Oeste",
    "lat": -40.73287677,
    "lng": -64.93328231,
    "pop": 8492,
    "country": "Argentina",
    "iso2": "AR",
    "iso3": "ARG",
    "province": "Río Negro",
    "timezone": "America/Argentina/Salta"
  },
  {
    "city": "San Pedro",
    "city_ascii": "San Pedro",
    "lat": -24.21962116,
    "lng": -64.87000452,
    "pop": 55249,
    "country": "Argentina",
    "iso2": "AR",
    "iso3": "ARG",
    "province": "Jujuy",
    "timezone": "America/Argentina/Jujuy"
  },
  {
    "city": "Salto",
    "city_ascii": "Salto",
    "lat": -31.39034625,
    "lng": -57.9686945,
    "pop": 102756.5,
    "country": "Uruguay",
    "iso2": "UY",
    "iso3": "URY",
    "province": "Salto",
    "timezone": "America/Montevideo"
  },
  {
    "city": "Salt Lake City",
    "city_ascii": "Salt Lake City",
    "lat": 40.7750163,
    "lng": -111.9300519,
    "pop": 572013,
    "country": "United States of America",
    "iso2": "US",
    "iso3": "USA",
    "province": "Utah",
    "state_ansi": "UT",
    "timezone": "America/Denver"
  },
]
